server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Liangxi1125
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
      maximum-pool-size: 10
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#  redis:
#    timeout: 10000ms
##    服务器地址
#    host:
##    端口号
#    port:
#    database: 0

  rabbitmq:
#    rabbitmq默认的用户与密码
    username: guest
    password: guest
    #    服务器地址
    host: localhost
    #    端口
    port: 5672
#    消息确认回调
    publisher-confirm-type: correlated
#    消息失败回调
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.yebProject.server.pojo
  configuration:
#    是否开启驼峰命名
    map-underscore-to-camel-case: false

logging:
  level:
    com.yebProject.server.mapper: debug



jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer


