#启动端口，使用邮件传输服务需要启动mail和server
server:
  port: 8082

spring:
  mail:
#    邮件服务器地址
    host: smtp.qq.com
#    协议
    protocol: smtp
#    默认编码
    default-encoding: utf-8
#    授权码（开启smtp服务时获取）
    password: orutrptlzytpdiec
#    发送者邮件地址
    username: 2373162039@qq.com
#    端口
    port: 25


  rabbitmq:
    username: guest
    password: guest
#    服务器地址
    host: localhost
#    端口
    port: 5672